project:
  type: website

website:
  title: "ISSS608-VAA Project Website"
  image: images/fisheye_rev.png
  open-graph: true
  site-url: "http:isss608-vast-2023-grp11.netlify.app"
  repo-url: "https://github.com/yawwwn/VAST-challenge-2023"
  navbar:
    background: "#f0eeeb"
    logo: image/fisheye_rev.png
    logo-alt: "ISSS608 VAA Group 11"
    title: false
    collapse-below: lg
    right:
      - text: "Home"
        href: "index.html"
      - text: "Shiny App"
        href: "https://junsok21.shinyapps.io/ShinyAppsGroup11/"
      - text: "Proposal"
        href: "Proposal/Proposal.html"
      - text: "User Guide"
        href: "userguide.html"
      - text: "Poster"
        href: "poster.html"
      - text: "Meeting Minutes"
        menu: 
        - text: "Meeting 1"
          href: Minutes/Minutes_01.qmd
        - text: "Meeting 2"
          href: Minutes/Minutes_02.qmd
        - text: "Meeting 3"
          href: Minutes/Minutes_03.qmd
        - text: "Meeting 4"
          href: Minutes/Minutes_04.qmd
        - text: "Meeting 5"
          href: Minutes/Minutes_05.qmd       
          
page-navigation: true

back-to-top-navigation: false

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
editor: visual
