project:
  type: website

website:
  title: "ISSS608-VAA Project Website"
  image: images/fisheye.png
  open-graph: true
  site-url: "http:isss608-vast-2023-grp11.netlify.app"
  repo-url: "https://github.com/yawwwn/VAST-challenge-2023"
  navbar:
    background: "#f0eeeb"
    logo: image/fisheye.png
    logo-alt: "Real World Data Science brand"
    title: false
    collapse-below: lg
    right:
      - text: "Home"
        href: "about.html"
      - text: "Proposal"
        href: "Proposal/Proposal.html"
      - text: "User Guide"
        href: "index.html"
      - text: "Poster"
        href: "index.html"
      - text: "Meeting Minutes"
        menu: 
        - text: "Meeting 1"
          href: Minutes/Minutes_01.qmd
page-navigation: true

back-to-top-navigation: false

format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto
editor: visual
