project:
  type: website

website:
  title: "ISSS608-VAA"
  site-url: "http:isss608-vast-2023-grp11.netlify.app"
  sidebar:
    background: "#A8D8CA"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents: 
          - text: "Intro"
            href: index.qmd
          - text: "About"
            href: about.qmd
      - section: "Proposal"
        contents:
          - text: "Proposal"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - section: "User Guide"
        contents:
          - text: "User Guide"
            href: ""
      - section: "Shiny App"
        contents: 
          - text: "Shiny App"
            href: ""
      - section: "Poster"
        contents: 
          - text: "Poster"
            href: ""            

format:
  html:
    theme: Tufte-LaTeX
    css: styles.css
    toc: true

editor: visual
