project:
  type: website

website:
  title: "ISSS608-VAA"
  site-url: 
  sidebar:
    background: "#A8D8CA"
    tools:
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents: 
          - text: "Intro"
            href: index.qmd
          - text: "About"
            href: about.qmd
      - section: "Hands-on Exercise"
        contents:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - section: "Take-Home Exercise"
        contents:
          - text: "Take-Home Exercise 1"
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
          - text: "Take-Home Exercise 2"
            href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
      - section: "In-Class Exercise"
        contents: 
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"

format:
  html:
    theme: Tufte-LaTeX
    css: styles.css
    toc: true

editor: visual

