project:
  type: website

website:
  title: "ISSS608-VAA Project Website"
  site-url: "http:isss608-vast-2023-grp11.netlify.app"
  sidebar:
    background: "#A8D8CA"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Home"
        contents: 
          - text: "Intro"
            href: index.qmd
          - text: "About"
            href: about.qmd
      - text: "Proposal"
        href: "Proposal/Proposal.html"
      - section: "Meeting Minutes"
        contents:
          - text: "Meeting 1"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%201st.docx?d=w38ef8b08f8c643418fda0ff0dee19570&csf=1&web=1&e=jIldbH"     
          - text: "Meeting 2"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs"   
          - text: "Meeting 2"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs1"
          - text: "Meeting 3"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs2"
          - text: "Meeting 4"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs3"
          - text: "Meeting 5"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs4"
          - text: "Meeting 6"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs5"
          - text: "Meeting 7"
            href: "https://smu.sharepoint.com/:w:/r/teams/ISSS608VAAGROUP11/Shared%20Documents/General/VAA%20Minutes%20of%20Meeting%202nd.docx?d=w450828f75dc74465a296bc1ab482e597&csf=1&web=1&e=oRSJzs6"          
      - section: "User Guide"
        contents:
          - text: "User Guide"
            href: ""
      - section: "Shiny App"
        contents: 
          - text: "Shiny App"
            href: ""
      - section: "Poster"
        contents: 
          - text: "Poster"
            href: ""            

format:
  html:
    theme: Tufte-LaTeX
    css: styles.css
    toc: true

editor: visual
