---
title: "Project Meeting 01"
description: "Sunday, 28th May 2023 from 1600 to 1800 <br> Microsoft Team Meeting<br>"
author:
  - name: Oh Jia Wen
    #url: 
date: '2023-06-03'
format: html
output:
  distill::distill_article:
    self_contained: false
    toc: true
editor_options: 
  markdown: 
    wrap: 106
---

# Agenda(s)

+---------------------------------------------------------------------------+
| 1.  Setting up Project Github and Project Website                         |
+---------------------------------------------------------------------------+
| 2.  Discussion on the topic for VAA Group Project                         |
+---------------------------------------------------------------------------+
| 3.  Selection of Topic                                                    |
+---------------------------------------------------------------------------+
| 4.  Review on next agenda(s)                                              |
+---------------------------------------------------------------------------+

# 1. Setting up Project Github and Website

Yao Wen created the Project Github and send invites to the team members before creating a new Project in
R. However, the team faced the issue of not being able to connect to Github. Jia Wen mentioned about the
version control option on Github. Yao Wen tested it and found out that it works before proceeding to
Netlify to create the website.

Junseok reviewed the previous video uploaded by Prof Kam and assisted in the creation of the website.
Thereafter, the team member took turn to commit and realized that changes are not reflected immediately.
Yao Wen discovered that we should do a `PULL` before rendering/commit to avoid conflicting entries.

# 2. Discussion of the Topic for VAA Group Project

The team members shared their opinions on the topic one by one to gain insights before drawing our
conclusion:

[Mini Case 1:]{.underline}

Jia Wen shared that the case does not seems to be as challenging as MC2 on first glance and is worth
checking it out as we are able to choose between this case and Mini Case 3 for our third exercise. Yao Wen
shared his concerns that Prof Kam mentioned the data set requires a lot of cleaning. Junseok tried to load
the data set into R and agreed with what Yao Wen said.

[Mini Case 2:]{.underline}

Junseok shared that this case might be more suitable for us as we are in the midst of doing Take Home
Exercise Two and have done the necessary data wrangling process. Jia Wen agreed and mentioned that she
have tried to address question two of the task. The hscode in particular, is an important factor as it is
a harmonized system. Yao Wen voiced his concern over the approach as each of us did a different approach
for question one but Jia Wen shared that we could combined our approaches for a best fit model.

[Mini Case 3:]{.underline}

Junseok shared that he imported the data into R and found out that there are no null values but more
analysis might be required. Jia Wen shared her concerns with regards to the business relationship as it is
pretty vague. It could be to Business-to-Business relationship (B2B), Business-to-Consumers relationship
(B2C) or it could be Distributor-Wholesaler- Retailers kind of relationship. Yao Wen shared that it might
be geared towards the B2B, B2C way.

# 3. Selection of Topic

For the selection of topic, our group have decided to choose **Mini Case 2** as our choice of project and
the reasoning for eliminating other cases are as follows:

-   Mini Case 1: Requires more data preparation which might be too time consuming and perceived ambiguity
    since data sets requires us to identify the four companies.

-   Mini Case 3: There are potential in this Mini Case if more information are being shared in class.
    However, the team felt that there are in comparison to Mini Case 2, we are less familiar with this
    topic since time has been invested in our take home exercise.

# 4. Review on Next Agenda(s)

The team has targeted to complete the project proposal in the next meeting and look beyond our question of
Take Home Exercise Two to see if we are able to address Question three and four of the challenge. The team
has agreed to meet after VAA class to discuss the approach and split the work allocation of the proposal.

# 5. End of Meeting

The meeting ended at 1800. The next meeting would convene on Saturday, 3rd June 2023 at 1600.
